In [2]:
# One-Hot Encoding 编码

# 将定性特征转化为定量特征，如sex=男/女 => sex为男：1，sex为女：0
# 编码主要有 DummyEncoding / One-hot Encoding

# 一个定性特征或者成为Categorical Variable,其有n个值
# Dummy Encoding 会将这个Categorical Variable转换为n-1个特征变量，而OneHot Encoding会转换为n个特征变量

In [31]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from scipy import sparse

In [32]:
# 使用pandas对dataframe进行one-hot编码

rawdata = pd.read_csv('./onehot.txt')

train_x = np.array(rawdata)

print(rawdata)
print("\n")
data = pd.get_dummies(rawdata, columns=['pet'])                                  # 经过one-hot编码

print(data)
print("\n")
# dummy-encoding

data2 = pd.get_dummies(rawdata, columns=['pet'], drop_first=True)                # 经过dummy-encoding（剔除了第一个变量）

print(data2)

   age   pet  salary
0    4   cat       4
1    6   dog       5
2    3   dog       1
3    3  fish       1


   age  salary  pet_cat  pet_dog  pet_fish
0    4       4      1.0      0.0       0.0
1    6       5      0.0      1.0       0.0
2    3       1      0.0      1.0       0.0
3    3       1      0.0      0.0       1.0


   age  salary  pet_dog  pet_fish
0    4       4      0.0       0.0
1    6       5      1.0       0.0
2    3       1      1.0       0.0
3    3       1      0.0       1.0


In [22]:
# 使用sklearn进行one-hot encoding
# sklearn中的OneHotEncoder提供fit(X),transform(X),fit_transform(X)
# 其中X是一个二维数组，且数组类型为int，不能直接处理字符串类型的Categorical Varibale OneHotEncoder后的编码长度是原来每个特征各自的类别数之和

sample = np.array([[0, 0, 3], [1, 1, 0], [0, 2, 1], [1, 0, 2]])

enc = OneHotEncoder()
enc.fit(sample)

print(enc.n_values_)         # 每个维度的类的个数
print(enc.feature_indices_)  # 特征的索引

[2 3 4]
[0 2 5 9]


In [25]:
# 通过sklearn进行字符串的one-hot-encoding
# 通过LabelEncoder把字符串类型定性特征转变为连续的数值型变量，再用OneHotEncoder二值化。 

lenc = LabelEncoder()
lenc_data = lenc.fit_transform(rawdata['pet'])
print(lenc_data)

[0 1 1 2]


In [28]:
enc = OneHotEncoder(sparse=False)
enc_data = enc.fit_transform(lenc_data.reshape(-1, 1))
print(enc_data)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
